//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_RadialMenu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.radialMenu_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.radialMenu_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.radialMenu_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.radialMenu_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.radialMenu_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.radialMenu_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.radialMenu_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.radialMenu_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMenuLeft
        {
            get
            {
                return SteamVR_Actions.radialMenu_ActivateMenuLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectLeft
        {
            get
            {
                return SteamVR_Actions.radialMenu_SelectLeft;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuSelectionPositionLeft
        {
            get
            {
                return SteamVR_Actions.radialMenu_MenuSelectionPositionLeft;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuSelectionPositionRight
        {
            get
            {
                return SteamVR_Actions.radialMenu_MenuSelectionPositionRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectRight
        {
            get
            {
                return SteamVR_Actions.radialMenu_SelectRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMenuRight
        {
            get
            {
                return SteamVR_Actions.radialMenu_ActivateMenuRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.radialMenu_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.radialMenu_Haptic;
            }
        }
    }
}
